name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clean Build Directory
      run: dotnet clean

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Clean Up Temporary Files
      run: rm ./obj ./bin ./publish

    - name: Package App
      run: dotnet publish --framework net9.0 --configuration Release

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: winui3-app
        path: ./publish
        retention-days: 1
