# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Clean Build Directory
      run: dotnet clean
  
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Clean Up Temporary Files
      run: rm -rf ./obj ./bin
      
    - name: Package App
      run: |
          dotnet publish --framework net9.0 --configuration Release --no-build

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: winui3-app
        retention-days: 1
