name: Package App

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  package:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Package App
      run: dotnet publish --framework net9.0 --configuration Release --output ./publish

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: winui3-app
        path: ./bin
